title: Jean Pierre Dudey | Blog
author: Jean Pierre Dudey
email: jeandudey@hotmail.com
description: >
  Jean Pierre Dudey's blog about programming in general.
show_excerpts: true

sass:
  sass_dir: _sass
plainwhite:
  name: Jean Pierre Dudey
  tagline: Systems Programmer
  date_format: "%b %-d, %Y"
  sitemap: true
  social_links:
    twitter: jeandudey
    github:  jeandudey
    rss: rss

plugins:
  - jekyll-seo-tag